/**
 * Project directory (.mrclean/) setup.
 *
 * Creates the .mrclean/ directory and a stub config.toml on first install.
 * Re-running does NOT clobber an existing config.toml (operator may have edited it).
 *
 * The config.toml stub is purely comments and empty section headers — no live key=value
 * lines. Plan 01-02b's config reader treats it as an empty layer (returns defaults).
 *
 * RESEARCH.md §7 (.mrclean/ contract), Phase 1 interface spec.
 */

import { mkdir, writeFile, access, constants, chmod } from 'node:fs/promises'
import { join } from 'node:path'

const CONFIG_TOML_STUB = `# mrclean project configuration
# See: https://github.com/mrclean/mrclean#configuration
#
# This file is auto-generated by \`mrclean install\`.
# You may edit it to add project-local overrides.
# By default, .mrclean/ is gitignored — to commit your config, remove
# the mrclean managed block from your project-root .gitignore manually.

[allowlist]
# rules = []      # Allowlist rule IDs (secretlint/gitleaks) to skip
# paths = []      # Glob patterns to exclude from scanning

[words]
# Additional proprietary terms to redact (plain strings).
# words = ["ACME Corp", "internal-api.acme.com"]

[detection]
# Enable/disable individual detection layers.
# layer1_secretlint = true
# layer2_entropy = true
# layer3_env = true
# layer4_words = true
`

export interface ProjectDirResult {
  created: boolean
  path: string
}

/**
 * Create the .mrclean/ directory in `cwd` and write a stub config.toml.
 *
 * - Directory created with mode 0755.
 * - config.toml written with mode 0644 only on first run.
 * - Returns `{ created: true, path }` on first creation.
 * - Returns `{ created: false, path }` if directory already exists (no-op for config.toml).
 */
export async function createProjectDir(cwd: string): Promise<ProjectDirResult> {
  const dirPath = join(cwd, '.mrclean')
  const configPath = join(dirPath, 'config.toml')

  // Create the directory (idempotent with recursive: true)
  let created = false
  try {
    await access(dirPath, constants.F_OK)
    // Directory exists — check if config.toml exists
    const configExists = await fileExists(configPath)
    if (!configExists) {
      await writeConfigStub(configPath)
    }
    created = false
  } catch {
    // Directory does not exist — create it
    await mkdir(dirPath, { recursive: true })
    await chmod(dirPath, 0o755)
    await writeConfigStub(configPath)
    created = true
  }

  return { created, path: dirPath }
}

// ---------------------------------------------------------------------------
// Internal helpers
// ---------------------------------------------------------------------------

async function fileExists(path: string): Promise<boolean> {
  try {
    await access(path, constants.F_OK)
    return true
  } catch {
    return false
  }
}

async function writeConfigStub(configPath: string): Promise<void> {
  await writeFile(configPath, CONFIG_TOML_STUB, { encoding: 'utf8', mode: 0o644 })
}
