/**
 * Unit tests for readConfigLayer.
 *
 * Covers: missing file → {}, empty file → {}, install-time stub → {},
 * dry_run override, allowlist.rules, malformed TOML → ConfigReadError.
 */

import { describe, it, expect, beforeEach, afterEach } from 'vitest'
import { readFile, writeFile, mkdir, rm } from 'node:fs/promises'
import { join } from 'node:path'
import { tmpdir } from 'node:os'
import { randomUUID } from 'node:crypto'
import { readConfigLayer, ConfigReadError } from '../../src/config/index.js'

// Exact stub content that createProjectDir writes (src/install/project-dir.ts).
// Cross-reference: if project-dir.ts changes CONFIG_TOML_STUB, update this too.
const INSTALL_STUB = `# mrclean project configuration
# See: https://github.com/mrclean/mrclean#configuration
#
# This file is auto-generated by \`mrclean install\`.
# You may edit it to add project-local overrides.
# By default, .mrclean/ is gitignored — to commit your config, remove
# the mrclean managed block from your project-root .gitignore manually.

[allowlist]
# rules = []      # Allowlist rule IDs (secretlint/gitleaks) to skip
# paths = []      # Glob patterns to exclude from scanning

[words]
# Additional proprietary terms to redact (plain strings).
# words = ["ACME Corp", "internal-api.acme.com"]

[detection]
# Enable/disable individual detection layers.
# layer1_secretlint = true
# layer2_entropy = true
# layer3_env = true
# layer4_words = true
`

describe('readConfigLayer', () => {
  let tmpDir: string

  beforeEach(async () => {
    tmpDir = join(tmpdir(), `mrclean-config-test-${randomUUID()}`)
    await mkdir(tmpDir, { recursive: true })
  })

  afterEach(async () => {
    await rm(tmpDir, { recursive: true, force: true })
  })

  // Test 1: missing file returns empty object
  it('resolves to {} when file does not exist', async () => {
    const result = await readConfigLayer(join(tmpDir, 'nonexistent', 'config.toml'))
    expect(result).toEqual({})
  })

  // Test 2: zero-byte file returns empty object
  it('resolves to {} when file is empty (zero bytes)', async () => {
    const emptyPath = join(tmpDir, 'config.toml')
    await writeFile(emptyPath, '')
    const result = await readConfigLayer(emptyPath)
    expect(result).toEqual({})
  })

  // Test 3: install-time stub round-trip (updated for Phase 2: smol-toml parses [allowlist]
  // header as an empty table, producing allowlist with all-empty arrays; this is semantically
  // equivalent to {} for mergeConfigs since empty arrays produce no contribution).
  it('resolves to empty allowlist shape when file is the install-time stub', async () => {
    const stubPath = join(tmpDir, 'config.toml')
    await writeFile(stubPath, INSTALL_STUB)
    const result = await readConfigLayer(stubPath)
    // smol-toml sees [allowlist] header → allowlist: {} → normalized to all-empty axes.
    // All other sections ([words], [detection]) are unknown and ignored.
    // The result is either {} or { allowlist: emptyAxes } — both are valid empty configs.
    const al = (result as { allowlist?: { rules: string[]; paths: string[] } }).allowlist
    if (al !== undefined) {
      expect(al.rules).toEqual([])
      expect(al.paths).toEqual([])
    }
    expect((result as { dry_run?: boolean }).dry_run).toBeUndefined()
    expect((result as { entropy?: unknown }).entropy).toBeUndefined()
    expect((result as { secrets_files?: unknown }).secrets_files).toBeUndefined()
  })

  // Test 4: dry_run override parses correctly
  it('returns { dry_run: true } when file contains `dry_run = true`', async () => {
    const configPath = join(tmpDir, 'config.toml')
    await writeFile(configPath, 'dry_run = true\n')
    const result = await readConfigLayer(configPath)
    expect(result).toEqual({ dry_run: true })
  })

  // Test 5: allowlist.rules inline array parses correctly
  it('returns allowlist.rules when file contains [allowlist] section with rules array', async () => {
    const configPath = join(tmpDir, 'config.toml')
    await writeFile(configPath, '[allowlist]\nrules = ["RULE-A", "RULE-B"]\n')
    const result = await readConfigLayer(configPath)
    expect((result as { allowlist?: { rules: string[] } }).allowlist?.rules).toEqual(['RULE-A', 'RULE-B'])
  })

  // Test 6: malformed TOML throws ConfigReadError (updated for Phase 2: smol-toml error
  // messages do not contain "malformed line" — they include smol-toml's own parse error text).
  it('throws ConfigReadError with path and reason when TOML is malformed', async () => {
    const configPath = join(tmpDir, 'config.toml')
    await writeFile(configPath, 'this is not toml = = =\n')
    await expect(readConfigLayer(configPath)).rejects.toBeInstanceOf(ConfigReadError)

    try {
      await readConfigLayer(configPath)
    } catch (err) {
      expect(err).toBeInstanceOf(ConfigReadError)
      const configErr = err as ConfigReadError
      expect(configErr.path).toBe(configPath)
      expect(configErr.reason).toBeTruthy()
      expect(configErr.message).toContain(configPath)
      // smol-toml provides its own error text; we don't assert a specific prefix.
    }
  })
})
